# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 21:23
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitsFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5sum', models.CharField(max_length=32, unique=True)),
                ('filesize', models.BigIntegerField()),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('ra', django.contrib.postgres.fields.ranges.FloatRangeField(help_text='RA min,max', null=True)),
                ('dec', django.contrib.postgres.fields.ranges.FloatRangeField(help_text='DEC min,max', null=True)),
                ('exposure', django.contrib.postgres.fields.ranges.FloatRangeField()),
                ('archive_filename', models.CharField(max_length=256)),
                ('date_obs', django.contrib.postgres.fields.ranges.DateRangeField(help_text='DATE-OBS min,max', null=True)),
                ('original_filename', models.CharField(max_length=256)),
                ('release_date', models.DateTimeField()),
                ('instrument', models.CharField(help_text='INSTRUME', max_length=80)),
                ('telescope', models.CharField(help_text='TELESCOP', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Hdu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hdu_idx', models.PositiveSmallIntegerField()),
                ('xtension', models.CharField(blank=True, max_length=40)),
                ('bitpix', models.IntegerField()),
                ('naxis', models.PositiveSmallIntegerField()),
                ('naxisN', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), default=list, size=None)),
                ('pcount', models.PositiveIntegerField(null=True)),
                ('gcount', models.PositiveIntegerField(null=True)),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField()),
                ('fitsfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natica.FitsFile')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_id', models.CharField(max_length=10, null=True, unique=True)),
                ('pi', models.CharField(max_length=40)),
                ('proprietary_period', models.SmallIntegerField()),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='fitsfile',
            name='proposal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='natica.Proposal'),
        ),
    ]
