# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-20 17:00
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionHDU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension_idx', models.PositiveSmallIntegerField()),
                ('xtension', models.CharField(max_length=40)),
                ('naxis', models.PositiveSmallIntegerField()),
                ('naxisN', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), size=None)),
                ('pcount', models.PositiveIntegerField()),
                ('gcount', models.PositiveIntegerField()),
                ('date_obs', models.DateTimeField(help_text='DATE-OBS')),
                ('obj', models.CharField(help_text='OBJECT', max_length=80)),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='FitsFile',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('filesize', models.BigIntegerField()),
                ('release_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryHDU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitpix', models.IntegerField()),
                ('naxis', models.PositiveSmallIntegerField()),
                ('naxisN', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), size=None)),
                ('instrument', models.CharField(help_text='INSTRUME', max_length=80)),
                ('telescope', models.CharField(help_text='TELESCOP', max_length=80)),
                ('date_obs', models.DateTimeField(help_text='DATE-OBS')),
                ('obj', models.CharField(help_text='OBJECT', max_length=80)),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField()),
                ('fitsfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natica.FitsFile')),
            ],
        ),
        migrations.AddField(
            model_name='extensionhdu',
            name='fitsfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natica.FitsFile'),
        ),
    ]
