# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-08 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('natica', '0002_auto_20170810_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('name', models.CharField(help_text='Name used in FITS header (field name INSTRUME)', max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('name', models.CharField(help_text='Site (mountain)', max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Telescope',
            fields=[
                ('name', models.CharField(help_text='Name used in FITS header (field name TELES', max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='fitsfile',
            name='archive_filename',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='fitsfile',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natica.Instrument'),
        ),
        migrations.AlterField(
            model_name='fitsfile',
            name='original_filename',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='fitsfile',
            name='telescope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natica.Telescope'),
        ),
    ]
