# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natica', '0003_auto_20170721_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionhdu',
            name='dec',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extensionhdu',
            name='ra',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='primaryhdu',
            name='dec',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='primaryhdu',
            name='ra',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
