# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natica', '0004_auto_20170721_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extensionhdu',
            name='date_obs',
            field=models.DateTimeField(help_text='DATE-OBS', null=True),
        ),
        migrations.AlterField(
            model_name='extensionhdu',
            name='dec',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='extensionhdu',
            name='ra',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='primaryhdu',
            name='date_obs',
            field=models.DateTimeField(help_text='DATE-OBS', null=True),
        ),
        migrations.AlterField(
            model_name='primaryhdu',
            name='dec',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='primaryhdu',
            name='ra',
            field=models.FloatField(null=True),
        ),
    ]
