# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natica', '0006_auto_20170722_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extensionhdu',
            name='dec',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='extensionhdu',
            name='ra',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
